### ISSUE TITLE
How to use Wireguard over Shadowsocks-Go?

### ISSUE THREAD

**Issue by thematrixdev** [shadowsocks/go-shadowsocks2#187]
Shadowsocks-Go is deployed with Docker. This is the Docker-Compose command:
`command: ["go-shadowsocks2", "-c", "ss://AEAD_CHACHA20_POLY1305:123456@ShadowSocksGoServerIP:8488", "-verbose", "-socks", "0.0.0.0:1080", "-u", "-udptun", "0.0.0.0:51820=WireGuardServerIP:51820"]`

Setting system proxy to 127.0.0.1:1080 it works.

This is the WireGuard configuration file:
`[Interface]
Address = 10.0.0.2/24
PrivateKey = KEYKEYKEYKEYKEY
DNS = 1.1.1.1

[Peer]
AllowedIPs = 0.0.0.0/0
Endpoint = 127.0.0.1:51820
PublicKey = KEYKEYKEYKEYKEY`

After starting WireGuard, there is no Internet connection. May I know what is wrong with these?

Thanks.

**Comment by riobard** [comment]
Are you sure you running _shadowsocks–go_ on the server side? AFAIK shadowsocks-go does not have UDP support and it is deprecated.

And just to be curious, why are you doing this?

**Comment by thematrixdev** [comment]
Sure, shadowsocks-go is runnin, since I can browse Internet seeing "my IP" is the server IP.

I see shadowsocks-go supports these
```
 SOCKS5 proxy with UDP Associate
 UDP tunneling (e.g. relay DNS packets)
```
That means UDP works via shadowsocks-go?

**Comment by thematrixdev** [comment]
By the way, I see in the example, 8.8.8.8 is tunneled on port 8053. May I know how to use this tunnel? Ubuntu 20.04 does not allow me setting a port number. Using OpenVPN, even 1.1.1.1 is set, it does not work.

I am now not inside GFW. But my company firewall blocks quite a lot of websites and services. I have tried Trojan buy my company blocks the domain name. So I am using Shadowsocks now. It seems running VPN over Shadowsocks a more secure solution.

**Comment by thematrixdev** [comment]
Yes, SSG2. No firewall is turned on on Ubuntu. Ports are opened on Vultr.

docker-compose.yml
```
version: '3.5'
services:
  shadowsocks-server:
    container_name: shadowsocks-server
    image: shadowsocks-server
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8488:8488/tcp"
      - "8488:8488/udp"
    command: ["go-shadowsocks2", "-s", "ss://AEAD_CHACHA20_POLY1305:123456@0.0.0.0:8488", "-verbose"]
    restart: always
```

```
FROM golang:alpine
RUN apk add git
RUN go get -u -v github.com/shadowsocks/go-shadowsocks2
```
